defaultContentLanguage = "ja"
baseURL = "http://voyagegroup.github.io/make-advent-calendar-2017-to-2018"
publishDir = "docs"
hasCJKLanguage = true
theme = "techdoc"

[frontmatter]
date  = [":filename", ":default"]

[languages]
[languages.ja]
title = "Makefile Advent Calender"
dateFormat = "2006年01月02日"

